### ISSUE TITLE
Error in rnagsva function

### ISSUE THREAD

**Issue by Rahel14350** [pcheng84/TCGAbrowser#1]
Dear Pil Cheng,
I am running TCGAbrowser. I have this error on the pathway analysis. I did the analysis last month without any error on the same same gene set and disease without any error. Can you please help me here:
require(GSVAdata)
data(c2BroadSets)
> gene <- "SOX10"
> SOX10.pat <- rnasubset(pat, rna, gene, 20)
> SOX10.gsva <- rnagsva(SOX10.pat, rna)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
In addition: Warning messages:
1: In .local(expr, gset.idx.list, ...) :
  383genes with constant expression values throuhgout the samples.
2: In .local(expr, gset.idx.list, ...) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
Many thanks in advance,
Rahel

**Comment by pcheng84** [comment]
Hi Rahel,

I fixed the rnagsva function. #2099462
It should work now. 

Cheers,
Phil

**Comment by Rahel14350** [comment]
Dear Phil,
Many thanks for your prompt reply. I updated T"TCGAbrowser" and run it again but I have this error. Can you please check it. Many thanks in advance, Rahel
Error in .local(expr, gset.idx.list, ...) : 
  unused argument (kcdf = "Poisson")

**Comment by pcheng84** [comment]
Hi Rahel,

Could you install the newest GSVA package and try again?

**Comment by Rahel14350** [comment]
Dear Phil,
I did it and now I have this error:
Error in rnagsva(folh1.rna, rna) : object 'lookup' not found

**Comment by pcheng84** [comment]
Okay I fixed the lookup object. Can you try again?

**Comment by Rahel14350** [comment]
I ran all again and it gives the same error! I did also update the GSVA and TCGAbrowser again ...

**Comment by pcheng84** [comment]
HI Rahel,

I updated the internal data and fixed some small errors. I hope it works now.

**Comment by Rahel14350** [comment]
Hi Phil,
Many thanks for all of your helps. Unfortunately, the error is still the same. Do you also get this error? I am repeating everything from RPUBs example and I get error ...
sox10.gsva <- rnagsva(sox10.rna, rna)
Error in rnagsva(sox10.rna, rna) : object 'lookup' not found
Many thanks,

**Comment by pcheng84** [comment]
Hi Rahel,

I tested it again and on a different machine with a fresh install, it should work now.

**Comment by Rahel14350** [comment]
Hi Phil,
It repeated the first error:
Error in .local(expr, gset.idx.list, ...) : 
  unused argument (kcdf = "Poisson")
I will use the gene list from last step and will use them in David. Hopefully it works there.
Many thanks for your help!

**Comment by Rahel14350** [comment]
Dear Phil,
I succeed to do the pathway analysis in David but the heatmap view in TCGAbrowser is more useful. Would you please let me know when this error is fixed.
Kind Regards,
Rahel

**Comment by pcheng84** [comment]
Hi Rahel,
The bugs should be fixed. Other users can run the functions without errors now too. You can pull the package and try again.
Cheers,
Phil

**Comment by pcheng84** [comment]
Hi Rahel,

Is the error still unused argument (kcdf = "Poisson")?
What version of GSVA do you have and are you using R 3.4.3?

Cheers,
Phil

**Comment by Rahel14350** [comment]
Hi Phil,
Yes the error is the same: Error in .local(expr, gset.idx.list, ...) : 
  unused argument (kcdf = "Poisson")
When I run rnagsva function like below, then it is working with a warning but the next step gives me error.
rnagsva <- function(pat2, rna) {
   setkey(pat2, gene2)
   d1.gsva <- as.matrix(rna[,pat2[!("middle"), name], with=F])
   rownames(d1.gsva) <- lookup$entrez[match(rna$Gene, lookup$gene)]
  gsva(d1.gsva, c2BroadSets, method = "gsva", min.sz=5, max.sz=500, mx.diff=TRUE, verbose=TRUE,rnaseq=TRUE)
 }
sox10.gsva <- rnagsva(sox10.rna, rna)
%
Warning messages:
1: In .local(expr, gset.idx.list, ...) :
  383genes with constant expression values throuhgout the samples.
2: In .local(expr, gset.idx.list, ...) :
  Since argument method!="ssgsea", genes with constant expression values are discarded.
####
folh1.gsvasig <- rnagsvasig(folh1.rna, folh1.gsva)
Error in getEAWP(object) : data object isn't of a recognized data class
#####
Here is my sessioninfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS
other attached packages:
 [1] MultiAssayExperiment_1.2.1 BiocInstaller_1.26.1      
 [3] GSVA_1.24.2                dplyr_0.7.4               
 [5] GSVAdata_1.12.0            hgu95a.db_3.2.3           
 [7] org.Hs.eg.db_3.4.1         GSEABase_1.38.2           
 [9] graph_1.54.0               annotate_1.54.0           
[11] XML_3.98-1.10              AnnotationDbi_1.38.2      
[13] IRanges_2.10.5             S4Vectors_0.14.7          
[15] Biobase_2.36.2             BiocGenerics_0.22.1       
[17] data.table_1.10.4-3        TCGA2STAT_1.2             
[19] TCGAbrowser_0.1.0          devtools_1.13.5           

Sorry, if I am wasting your time ...
Rahel

**Comment by pcheng84** [comment]
Hi Rahel,

Could you update GSVA and try again?
It should be version 1.26

Don't worry I want this package to work for everyone.

Cheers,
Phil

**Comment by Rahel14350** [comment]
Hi Phil,
Thank you, Thank you so much. I updated GSVA to 1.26 using source package and GSVAdata to 1.14 and everything worked like beginning. Many thanks again,
Kind Regards,
Rahel
